### ISSUE TITLE
App won't install since version 19.0 or crashes in my device

### ISSUE THREAD

**Issue by El-Desconocido** [soupslurpr/BeauTyXT#162]
Accrescent does absolutely nothing when trying to install the app. Installing manually from releases will return a simple "app not installed" dialog. Installing any version prior to 19.0 will install and open succesfully, but it crashes after trying to create or open ANY file or folder. Maybe my device is too old for this, but if you wanna check this, my device is a Xiaomi Redmi 9C with Android version: 10 QP1A.190711.020.

**Comment by soupslurpr** [comment]
@El-Desconocido your device is using a 32-bit OS. BeauTyXT doesn't support 32-bit OS'. 32-bit OS' are worse for security than 64-bit OS'.

Before 0.19.0, BeauTyXT didn't explicitly say it didn't support 32-bit, but it didn't include 32-bit native libraries which is why it installs but crashes when trying to open or create a file or folder.

I highly recommend using GrapheneOS on a recommended device (https://grapheneos.org/faq#recommended-devices). GrapheneOS also has support for MTE (along with many other privacy/security improvements listed at https://grapheneos.org/features), which BeauTyXT opts-in to for better protection from exploit attempts.
