### ISSUE TITLE
Incorrect return behavior when opening from Intent

### ISSUE THREAD

**Issue by harish-kumaran** [soupslurpr/BeauTyXT#27]
When opening a text file from the file manager, the file gets opened and then when I press back, I don't get to the file manager, but rather it opens BeauTyXT's homepage then pressing back again it now comes back to the file manager screen.

I think making it to come back to the previous apps screen would be better just like the Secure PDF viewer.

**Comment by soupslurpr** [comment]
Yeah, I am aware of this. It is because of the way that I implemented opening a file from an intent. Basically right now it always opens up the main activity and it checks if there is an intent, if there is then it opens that file. Still a valid issue, just not going to be a priority since it seems like it might not be completely straightforward to fix it since I may have to add another activity specifically for opening from an intent or something else.
