### ISSUE TITLE
Open other file types compatible with text

### ISSUE THREAD

**Issue by Niko4u5** [soupslurpr/BeauTyXT#3]
It would be neat to edit other file types like configs etc.

**Comment by soupslurpr** [comment]
I can set it so that it is possible to choose any type of file, but I would like to make it a choice just so its easy to choose .txt and get only .txt files. I will most likely add an additional option to be able to open any type of file.

**Comment by soupslurpr** [comment]
donzo!

**Comment by soupslurpr** [comment]
I reverted the commit. I am instead going to go with an approach where I only add specific mime types that can be viewed and edited the same as text files to avoid the user opening images, videos, zip's, and other files that are not compatible with editing as text, since that was not the intention of this feature.

**Comment by soupslurpr** [comment]
In the future I will add an option or button with a warning to open any file type, even ones not compatible with text, such as images or videos. Not high priority though, since it seems a bit niche.
